name: viertoregym
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  get: ^4.7.3
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


  fonts:
    - family: Arial
      fonts:
        - asset: assets/Arial/Arial.ttf
        - asset: assets/Arial/Arial Bold.ttf
          weight: 700
